branches:
  only:
    - master
    - 
matrix:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty

language: bash

sudo: required

git:
  depth: 1

before_install:
  - sudo wget https://raw.githubusercontent.com/metalbote/team-development-server/master/install.sh

install:
  - sudo -H bash install.sh

before_script:
  - cd /usr/local/share/team-development-server

script:
  - sudo bash start-containers.sh
  - bash tests/container-run-test.sh
  - bash tests/container-reachable-test.sh



