os: linux
dist: xenial

language: bash

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo apt-get update

install:
  - bash init-environment.sh

script:
  - docker ps --filter="name=proxy" -q

after_script:
  - bash destroy-environment.sh

after_failure:
  - cat install.log

