os: linux
dist: xenial

language: bash

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo apt-get update
  - docker --version
  - docker ps

