os: linux
dist: xenial

language: bash

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo apt-get update

install:
  - bash services/init-environment.sh

script:
  - bash services/test-environment.sh

after_script:
  - bash services/destroy-environment.sh


