os: linux
dist: xenial

language: bash

sudo: required

git:
  depth: 1

before_install:
  - sudo wget https://raw.githubusercontent.com/metalbote/team-development-server/master/install.sh

install:
  - sudo -H bash install.sh

before_script:
  - cd /var/team-development-server

script:
  - sudo bash start-containers.sh
  - bash tests/container-run-test.sh
  - bash tests/container-reachable-test.sh



