os: linux
dist: xenial

language: bash

sudo: required

git:
  depth: 1


install:
  - sudo -H bash install.sh

before_script:
  - cd /var/team-development-server

script:
  - sudo bash start-containers.sh
  - bash tests/container-run-test.sh
  - bash tests/container-reachable-test.sh



