version: "3.6"
services:

  devshop:
    image: aegir/hostmaster
    container_name: "devshop"
    domainname: ${TDS_DOMAINNAME}
    hostname: "devshop"
    restart: always
    stop_grace_period: 30s
    ports:
      - ${TDS_DEVSHOP_SSHPORT}:22/tcp
    networks:
      private:
        aliases:
          - dev
          - devshop
      public:
        aliases:
          - dev.${TDS_DOMAINNAME}
          - devshop.${TDS_DOMAINNAME}
    environment:
      AEGIR_VERSION: "7.x-3.170"
      PROVISION_VERSION: "7.x-3.172"
      AEGIR_CLIENT_EMAIL: "${TDS_BRANDING_INFO_EMAIL}"
      AEGIR_MAKEFILE: "https://raw.githubusercontent.com/opendevshop/devshop/1.5.0-rc6/build-devmaster.make"
      AEGIR_PROFILE: "devmaster"
      AEGIR_HOSTMASTER_ROOT: "/var/aegir/devmaster"
      AEGIR_UID: 1000
      AEGIR_DATABASE_SERVER: devshopdb
      MYSQL_ROOT_PASSWORD: ${TDS_MYSQL_ROOT_PASSWORD}
    links:
      - devshopdb
    depends_on:
      - devshopdb
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${TDS_VOLUMEDIR}/devshop/data:/var/aegir"
    labels:
      traefik.enable: "true"
      traefik.backend: "devshop"
      traefik.docker.network: "public"
      traefik.port: "80"
      traefik.frontend.rule: "Host: devshop.${TDS_DOMAINNAME}"

  devshopdb:
    image: mariadb:latest
    container_name: "devshopdb"
    domainname: ${TDS_DOMAINNAME}
    hostname: "devshopdb"
    restart: always
    stop_grace_period: 30s
    networks:
      private:
        aliases:
          - devshopdb
      public:
        aliases:
          - devshopdb.${TDS_DOMAINNAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${TDS_MYSQL_ROOT_PASSWORD}
    volumes:
      - "${TDS_VOLUMEDIR}/devshop/mysql:/var/lib/mysql"

networks:
  public:
    external:
      name: public
  private:
    external:
      name: private

