version: "3.6"
services:

  traefik:
    env_file: .env
    image: traefik:latest
    hostname: proxy
    domainname: ${TDS_DOMAINNAME}
    container_name: "proxy"
    restart: always
    command: --api --docker
    ports:
      - 80:80/tcp
      - 443:443/tcp
    networks:
      private:
        aliases:
          - traefik
          - proxy
      public:
        aliases:
          - traefik.${TDS_DOMAINNAME}
          - proxy.${TDS_DOMAINNAME}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${TDS_VOLUMEDIR}/traefik/traefik.toml:/traefik.toml"
      - "${TDS_VOLUMEDIR}/traefik/certs/:/certs/"
    #     - "${TDS_VOLUMEDIR}/.config/traefik/:/acme.json"
    labels:
      traefik.enable: "true"
      traefik.backend: "proxy"
      traefik.docker.network: "public"
      traefik.port: "8080"
      traefik.frontend.rule: "Host:proxy.${TDS_DOMAINNAME}"

  portainer:
    env_file: .env
    image: portainer/portainer:latest
    container_name: "portainer"
    restart: always
    command: -H unix:///var/run/docker.sock --logo "${TDS_BRANDING_LOGO_URL}"
    networks:
      private:
        aliases:
          - portainer
      public:
        aliases:
          - portainer.${TDS_DOMAINNAME}
    environment:
      TZ: "${TDS_TIMEZONE}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${TDS_VOLUMEDIR}/portainer/data:/data"
    labels:
      traefik.enable: "true"
      traefik.backend: "portainer"
      traefik.docker.network: "public"
      traefik.port: "9000"
      traefik.frontend.rule: "Host:portainer.${TDS_DOMAINNAME}"

  mailhog:
    env_file: .env
    image: mailhog/mailhog:latest
    container_name: "mailhog"
    restart: always
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    networks:
      private:
        aliases:
          - mailhog
          - mail
      public:
        aliases:
          - mailhog.${TDS_DOMAINNAME}
          - mail.${TDS_DOMAINNAME}
    volumes:
      - "${TDS_VOLUMEDIR}/mailhog/mails:/maildir"
    labels:
      traefik.enable: "true"
      traefik.backend: "mailhog"
      traefik.docker.network: "public"
      traefik.port: "8025"
      traefik.frontend.rule: "Host:mail.${TDS_DOMAINNAME}"

  gitea:
    env_file: .env
    image: gitea/gitea:latest
    container_name: "gitea"
    domainname: ${TDS_DOMAINNAME}
    hostname: "gitea"
    restart: always
    stop_grace_period: 30s
    ports:
      - ${TDS_GIT_SSHPORT}:22/tcp
    networks:
      private:
        aliases:
          - gitea
          - git
      public:
        aliases:
          - gitea.${TDS_DOMAINNAME}
          - git.${TDS_DOMAINNAME}
    environment:
      APP_NAME: "${TDS_BRANDING_COMPANY_NAME} GIT Versioning Server"
      RUN_MODE: dev
      SSH_DOMAIN: gitea.${TDS_DOMAINNAME}
      SSH_PORT: ${TDS_GIT_SSHPORT}
      DISABLE_SSH: "false"
      HTTP_PORT: 3000
      ROOT_URL: "http://gitea.${TDS_DOMAINNAME}"
      DB_TYPE: mysql
      DB_HOST: gitdb.${TDS_DOMAINNAME}:3306
      DB_NAME: gitea
      DB_USER: ${TDS_MYSQL_GITEAUSER}
      DB_PASSWD: ${TDS_MYSQL_GITEAPWD}
      INSTALL_LOCK: "FALSE"
      DISABLE_REGISTRATION: "FALSE"
      REQUIRE_SIGNIN_VIEW: "TRUE"
      USER_UID: ${TDS_GIT_USER_UID}
      USER_GID: ${TDS_GIT_USER_GID}
    depends_on:
      - giteadb
    volumes:
      - "${TDS_VOLUMEDIR}/gitea/data:/data"
      - "${TDS_GIT_REPO_DIR}:/data/git/repositories"
    labels:
      traefik.enable: "true"
      traefik.backend: "gitea"
      traefik.docker.network: "public"
      traefik.port: "3000"
      traefik.frontend.rule: "Host: gitea.${TDS_DOMAINNAME}"

  giteadb:
    env_file: .env
    image: mariadb:latest
    container_name: "giteadb"
    domainname: ${TDS_DOMAINNAME}
    hostname: "giteadb"
    restart: always
    stop_grace_period: 30s
    networks:
      private:
        aliases:
          - gitdb
      public:
        aliases:
          - gitdb.${TDS_DOMAINNAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${TDS_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${TDS_MYSQL_GITEAUSER}
      MYSQL_PASSWORD: ${TDS_MYSQL_GITEAPWD}
      MYSQL_DATABASE: gitea
    volumes:
      - "${TDS_VOLUMEDIR}/gitea/mysql:/var/lib/mysql"

  pma:
    env_file: .env
    image: phpmyadmin/phpmyadmin:latest
    container_name: "pma"
    hostname: pma
    domainname: ${TDS_DOMAINNAME}
    restart: always
    networks:
      private:
        aliases:
          - pma
      public:
        aliases:
          - pma.${TDS_DOMAINNAME}
    external_links:
      - giteadb
    environment:
      PMA_ABSOLUTE_URI: "http://pma.${TDS_DOMAINNAME}"
      PMA_HOSTS: "gitdb.${TDS_DOMAINNAME}"
      PMA_PORT: "3306"
      PHP_UPLOAD_MAX_FILESIZE: "1G"
      PHP_MAX_INPUT_VARS: "1G"
      MYSQL_ROOT_PASSWORD: ${TDS_MYSQL_ROOT_PASSWORD}
    labels:
      traefik.enable: "true"
      traefik.backend: "pma"
      traefik.docker.network: "public"
      traefik.port: "80"
      traefik.frontend.rule: "Host:pma.${TDS_DOMAINNAME}"

networks:
  public:
    driver: bridge
    name: public
  private:
    name: private
