version: "2.4"
services:

  #-- Main Infrastructure

  tds_proxy:
    env_file: .env
    image: traefik:latest
    hostname: proxy
    domainname: ${TDS_DOMAINNAME}
    container_name: "tds_proxy"
    restart: always
    command: --web --api --docker --docker.domain=${TDS_DOMAINNAME}
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 8080:8080/tcp
    networks:
      private:
        aliases:
          - tds_proxy
          - proxy
      public:
        aliases:
          - proxy.${TDS_DOMAINNAME}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./services/traefik/config/traefik.toml:/traefik.toml"
      # - "./services/traefik/config/acme.json:/acme.json"
      - "./services/traefik/logs/access_traefik.log:/var/log/access_traefik.log"
      - "./services/traefik/logs/traefik.log:/var/log/traefik.log"
      - "./services/traefik/certs/:/certs/"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "tds_public"
      traefik.port: "8080"
      traefik.backend: "tds_proxy"
      traefik.sub.frontend.headers.SSLRedirect: "true"
      traefik.sub.frontend.entryPoints: "http,https"
      traefik.sub.frontend.passHostHeader: "true"
      traefik.sub.frontend.auth.basic: "${TDS_TRAEFIK_DASHBOARD_USER}:${TDS_TRAEFIK_DASHBOARD_HTPASSWD}"
      traefik.sub.frontend.rule: "Host: proxy.${TDS_DOMAINNAME}"

  tds_portainer:
    env_file: .env
    image: portainer/portainer:latest
    container_name: "tds_portainer"
    restart: always
    command: -H unix:///var/run/docker.sock --logo "${TDS_PORTAINER_LOGO_URL}"
    networks:
      private:
        aliases:
          - tds_portainer
      public:
        aliases:
          - portainer.${TDS_DOMAINNAME}
    environment:
      TZ: "${TDS_PORTAINER_TIMEZONE}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./services/portainer/data:/data"
      - "./services/portainer/config/templates/templates.json:/templates.json"
    labels:
      traefik.enable: "true"
      traefik.backend: "portainer"
      traefik.docker.network: "tds_public"
      traefik.port: "9000"
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.entryPoints: "http,https"
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.rule: "Host: portainer.${TDS_DOMAINNAME}, www.portainer.${TDS_DOMAINNAME}"

  tds_mailhog:
    env_file: .env
    image: mailhog/mailhog:latest
    container_name: "tds_mailhog"
    restart: always
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    networks:
      private:
        aliases:
          - tds_mailhog
          - mailhog
          - mail
      public:
        aliases:
          - mailhog.${TDS_DOMAINNAME}
          - mail.${TDS_DOMAINNAME}
    volumes:
      - "./services/mailhog/data/mails:/maildir"
    labels:
      traefik.enable: "true"
      traefik.backend: "tds_mailhog"
      traefik.docker.network: "tds_public"
      traefik.port: "8025"
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.entryPoints: "http,https"
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.rule: "Host: mail.${TDS_DOMAINNAME}, www.mail.${TDS_DOMAINNAME}"

  tds_pma:
    env_file: .env
    image: phpmyadmin/phpmyadmin:latest
    container_name: "tds_pma"
    hostname: pma
    domainname: ${TDS_DOMAINNAME}
    restart: always
    networks:
      private:
        aliases:
          - pma
      public:
        aliases:
          - pma.${TDS_DOMAINNAME}
    environment:
      PMA_ABSOLUTE_URI: "https://pma.${TDS_DOMAINNAME}"
      PMA_HOSTS: "giteadb,tds_php-censor-db"
      PMA_PORT: "3306"
      PHP_UPLOAD_MAX_FILESIZE: "1G"
      PHP_MAX_INPUT_VARS: "1G"
      MYSQL_ROOT_PASSWORD: ${TDS_MYSQL_ROOT_PASSWORD}
    labels:
      traefik.enable: "true"
      traefik.backend: "pma"
      traefik.docker.network: "tds_public"
      traefik.port: "80"
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.entryPoints: "http,https"
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.rule: "Host: pma.${TDS_DOMAINNAME}, www.pma.${TDS_DOMAINNAME}"


  #-- Versioning

  tds_gitea:
    env_file: .env
    image: gitea/gitea:latest
    container_name: "tds_gitea"
    domainname: ${TDS_DOMAINNAME}
    hostname: "gitea"
    restart: always
    stop_grace_period: 30s
    ports:
      - ${TDS_GITEA_SSHPORT}:22/tcp
    networks:
      private:
        aliases:
          - gitea.${TDS_DOMAINNAME}
          - gitea
      public:
        aliases:
          - git.${TDS_DOMAINNAME}
    external_links:
      - tds_proxy
    environment:
      APP_NAME: "${TDS_BRANDING_NAME} GIT Versioning Server"
      RUN_MODE: dev
      SSH_DOMAIN: gitea.${TDS_DOMAINNAME}
      SSH_PORT: ${TDS_GITEA_SSHPORT}
      DISABLE_SSH: "false"
      HTTP_PORT: 443
      ROOT_URL: "https://gitea.${TDS_DOMAINNAME}"
      DB_TYPE: mysql
      DB_HOST: tds_giteadb:3306
      DB_NAME: ${TDS_MYSQL_GITEA_DATABASE}
      DB_USER: ${TDS_MYSQL_GITEA_USER}
      DB_PASSWD: ${TDS_MYSQL_GITEA_PASSWORD}
      INSTALL_LOCK: "FALSE"
      DISABLE_REGISTRATION: "FALSE"
      REQUIRE_SIGNIN_VIEW: "TRUE"
      USER_UID: ${TDS_GITEA_USER_UID}
      USER_GID: ${TDS_GITEA_USER_GID}
    volumes:
      - "./services/gitea/data:/data"
      - "./services/gitea/config/style/css:/data/gitea/public/css"
      - "./services/gitea/config/style/img:/data/gitea/public/img"
      - "${TDS_REPO_DIR}:/data/git/repositories"
    labels:
      traefik.enable: "true"
      traefik.backend: "tds_gitea"
      traefik.docker.network: "tds_public"
      traefik.port: "3000"
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.entryPoints: "http,https"
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.rule: "Host: gitea.${TDS_DOMAINNAME}, www.gitea.${TDS_DOMAINNAME}"

  tds_giteadb:
    env_file: .env
    image: mariadb:latest
    container_name: "tds_giteadb"
    domainname: ${TDS_DOMAINNAME}
    hostname: "tds_giteadb"
    restart: always
    stop_grace_period: 30s
    networks:
      private:
        aliases:
          - tds_giteadb
    environment:
      MYSQL_ROOT_PASSWORD: ${TDS_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${TDS_MYSQL_GITEA_DATABASE}
      MYSQL_USER: ${TDS_MYSQL_GITEA_USER}
      MYSQL_PASSWORD: ${TDS_MYSQL_GITEA_PASSWORD}
    volumes:
      - "./services/gitea/mysql:/var/lib/mysql"
    labels:
      traefik.enable: "false"

  #-- CD/CI

  tds_php-censor-web:
    env_file: .env
    image: "phpcensor/php-censor-web:latest"
    container_name: "tds_php-censor-web"
    domainname: ${TDS_DOMAINNAME}
    restart: always
    stop_grace_period: 30s
    networks:
      private:
        aliases:
          - tds_php-censor-web
      public:
        aliases:
          - php-censor.${TDS_DOMAINNAME}
    external_links:
      - tds_proxy
    environment:
      - DB_HOST=tds_php-censor-db
      - DB_USER=${TDS_MYSQL_PHPCENSOR_USER}
      - DB_PASS=${TDS_MYSQL_PHPCENSOR_PASSWORD}
      - DB_NAME=${TDS_MYSQL_PHPCENSOR_DATABASE}
      - BEANSTALK_HOST=tds_php-censor-queue
      - BEANSTALK_QUEUE_NAME=phpcensor
      - DB_TYPE=mysql
      - DB_PORT=3306
      - SITE_URL=https://php-censor.${TDS_DOMAINNAME}
      - GITHUB_TOKEN=${TDS_PHPCENSOR_GITHUB_TOKEN}
      - ADMIN_NAME=${TDS_PHPCENSOR_ADMIN_USER}
      - ADMIN_EMAIL=${TDS_INFO_EMAIL}
      - ADMIN_PASSWORD=${TDS_PHPCENSOR_ADMIN_PASSWORD}
    labels:
      traefik.enable: "true"
      traefik.backend: "tds_php-censor"
      traefik.docker.network: "tds_public"
      traefik.port: "80"
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.entryPoints: "http,https"
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.rule: "Host: php-censor.${TDS_DOMAINNAME}, www.php-censor.${TDS_DOMAINNAME}"

  tds_php-censor-db:
    env_file: .env
    image: mariadb:latest
    container_name: "tds_php-censor-db"
    domainname: ${TDS_DOMAINNAME}
    hostname: "tds_php-censor-db"
    restart: always
    stop_grace_period: 30s
    networks:
      private:
        aliases:
          - tds_php-censor-db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "false"
      MYSQL_ROOT_PASSWORD: ${TDS_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${TDS_MYSQL_PHPCENSOR_DATABASE}
      MYSQL_USER: ${TDS_MYSQL_PHPCENSOR_USER}
      MYSQL_PASSWORD: ${TDS_MYSQL_PHPCENSOR_PASSWORD}
    volumes:
      - "./services/php-censor/mysql:/var/lib/mysql"
    labels:
      traefik.enable: "false"

  tds_php-censor-worker:
    env_file: .env
    image: "phpcensor/php-censor-worker:latest"
    container_name: "tds_php-censor-worker"
    restart: always
    stop_grace_period: 30s
    networks:
      private:
        aliases:
          - tds_php-censor-worker
    environment:
      - DB_HOST=tds_php-censor-db
      - DB_USER=${TDS_MYSQL_PHPCENSOR_USER}
      - DB_PASS=${TDS_MYSQL_PHPCENSOR_PASSWORD}
      - DB_NAME=${TDS_MYSQL_PHPCENSOR_DATABASE}
      - BEANSTALK_HOST=tds_php-censor-queue
      - BEANSTALK_QUEUE_NAME=phpcensor
      - DB_TYPE=mysql
      - DB_PORT=3306
      - SITE_URL=https://php-censor.${TDS_DOMAINNAME}
      - GITHUB_TOKEN=${TDS_PHPCENSOR_GITHUB_TOKEN}
      - ADMIN_NAME=${TDS_PHPCENSOR_ADMIN_USER}
      - ADMIN_EMAIL=${TDS_INFO_EMAIL}
      - ADMIN_PASSWORD=${TDS_PHPCENSOR_ADMIN_PASSWORD}
    labels:
      traefik.enable: "false"

  tds_php-censor-queue:
    env_file: .env
    image: "schickling/beanstalkd"
    container_name: "tds_php-censor-queue"
    networks:
      private:
        aliases:
          - tds_php-censor-queue
    labels:
      traefik.enable: "false"

networks:
  public:
    driver: bridge
    name: tds_public
  private:
    name: tds_private

