version: "3.6"
services:

  #-- Main Infrastructure

  tds_proxy:
    env_file: .env
    image: traefik:latest
    hostname: proxy
    domainname: ${TDS_DOMAINNAME}
    container_name: "tds_proxy"
    restart: always
    command: --web --api --docker --docker.domain=${TDS_DOMAINNAME}
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 8080:8080/tcp
    networks:
      private:
        aliases:
          - tds_proxy
          - proxy
      public:
        aliases:
          - proxy.${TDS_DOMAINNAME}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./services/traefik/config/traefik.toml:/traefik.toml"
      - "./services/traefik/certs/:/certs/"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "tds_public"
      traefik.port: "8080"
      traefik.backend: "tds_proxy"
      traefik.frontend.entryPoints: "http,https"
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.auth.basic: "${TDS_TRAEFIK_DASHBOARD_USER}:${TDS_TRAEFIK_DASHBOARD_HTPASSWD}"
      traefik.frontend.rule: "Host: proxy.${TDS_DOMAINNAME}"

  tds_portainer:
    env_file: .env
    image: portainer/portainer:latest
    container_name: "tds_portainer"
    privileged: true
    restart: always
    command: -H unix:///var/run/docker.sock --template-file /templates.json --logo ${TDS_PORTAINER_LOGO_URL}
    networks:
      private:
        aliases:
          - tds_portainer
      public:
        aliases:
          - portainer.${TDS_DOMAINNAME}
    environment:
      TZ: "${TDS_TIMEZONE}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "tds-portainer-data:/data"
      - "./services/portainer/public/css:/public/css"
      - "./services/portainer/config/templates/templates-1.20.0.json:/templates.json"
    labels:
      traefik.enable: "true"
      traefik.backend: "portainer"
      traefik.docker.network: "tds_public"
      traefik.port: "9000"
      traefik.frontend.entryPoints: "http,https"
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.rule: "Host: portainer.${TDS_DOMAINNAME}, www.portainer.${TDS_DOMAINNAME}"

  tds_mailhog:
    env_file: .env
    image: mailhog/mailhog:latest
    container_name: "tds_mailhog"
    restart: always
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    ports:
      - ${TDS_MAIL_SMTPPORT}:1025/tcp
    networks:
      private:
        aliases:
          - tds_mailhog
          - mailhog
          - mail
      public:
        aliases:
          - mailhog.${TDS_DOMAINNAME}
          - mail.${TDS_DOMAINNAME}
    volumes:
      - "tds-mailhog-data:/maildir"
    labels:
      traefik.enable: "true"
      traefik.backend: "tds_mailhog"
      traefik.docker.network: "tds_public"
      traefik.port: "8025"
      traefik.frontend.entryPoints: "http,https"
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.rule: "Host: mail.${TDS_DOMAINNAME}, www.mail.${TDS_DOMAINNAME}"

  tds_pma:
    env_file: .env
    image: phpmyadmin/phpmyadmin:latest
    container_name: "tds_pma"
    hostname: pma
    domainname: ${TDS_DOMAINNAME}
    restart: always
    networks:
      private:
        aliases:
          - pma
      public:
        aliases:
          - pma.${TDS_DOMAINNAME}
    environment:
      PMA_ABSOLUTE_URI: "http://pma.${TDS_DOMAINNAME}"
      PMA_HOST: "tds_giteadb"
      #PMA_HOSTS: "tds_giteadb"
      PMA_PORT: "3306"
      #PMA_PORTS: 3306
      PHP_UPLOAD_MAX_FILESIZE: "1G"
      PHP_MAX_INPUT_VARS: "1G"
      MYSQL_ROOT_PASSWORD: ${TDS_MYSQL_ROOT_PASSWORD}
    labels:
      traefik.enable: "true"
      traefik.backend: "pma"
      traefik.docker.network: "tds_public"
      traefik.port: "80"
      traefik.frontend.entryPoints: "http,https"
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.rule: "Host: pma.${TDS_DOMAINNAME}, www.pma.${TDS_DOMAINNAME}"

  #-- Versioning

  tds_gitea:
    env_file: .env
    image: gitea/gitea:latest
    container_name: "tds_gitea"
    domainname: ${TDS_DOMAINNAME}
    hostname: "gitea"
    restart: always
    stop_grace_period: 30s
    ports:
      - ${TDS_GITEA_SSHPORT}:22/tcp
    networks:
      private:
        aliases:
          - gitea.${TDS_DOMAINNAME}
          - tds_gitea
          - gitea
      public:
        aliases:
          - gitea.${TDS_DOMAINNAME}
    environment:
      APP_NAME: "${TDS_BRANDING_NAME} - GIT Versioning Server"
      RUN_MODE: prod
      PROTOCOL: "http"
      DOMAIN: gitea.${TDS_DOMAINNAME}
      ROOT_URL: "http://gitea.${TDS_DOMAINNAME}"
      HTTP_ADDR: 0.0.0.0
      HTTP_PORT: 3000
      DISABLE_SSH: "false"
      START_SSH_SERVER: "true"
      SSH_DOMAIN: gitea.${TDS_DOMAINNAME}
      SSH_PORT: ${TDS_GITEA_SSHPORT}
      SSH_LISTEN_PORT: ${TDS_GITEA_SSHPORT}
      OFFLINE_MODE: "false"
      ENABLE_GZIP: "true"
      LANDING_PAGE: explore
      DB_TYPE: mysql
      DB_HOST: tds_giteadb:3306
      DB_NAME: ${TDS_MYSQL_GITEA_DATABASE}
      DB_USER: ${TDS_MYSQL_GITEA_USER}
      DB_PASSWD: ${TDS_MYSQL_GITEA_PASSWORD}
      INSTALL_LOCK: "false"
      DISABLE_REGISTRATION: "false"
      REQUIRE_SIGNIN_VIEW: "true"
      USER_UID: ${TDS_GITEA_USER_UID}
      USER_GID: ${TDS_GITEA_USER_GID}
    volumes:
      - "tds-gitea-data:/data"
      - "./services/gitea/public:/data/gitea/public"
      - "./services/gitea/templates:/data/gitea/templates"
      - "${TDS_REPO_DIR}:/data/git/repositories"
    labels:
      traefik.enable: "true"
      traefik.backend: "tds_gitea"
      traefik.docker.network: "tds_public"
      traefik.port: "3000"
      traefik.frontend.entryPoints: "http"
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.rule: "Host: gitea.${TDS_DOMAINNAME}, www.gitea.${TDS_DOMAINNAME}"

  tds_giteadb:
    env_file: .env
    image: mariadb:latest
    container_name: "tds_giteadb"
    domainname: ${TDS_DOMAINNAME}
    hostname: "tds_giteadb"
    restart: always
    stop_grace_period: 30s
    networks:
      private:
        aliases:
          - tds_giteadb
          - giteadb
    environment:
      MYSQL_ROOT_PASSWORD: ${TDS_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${TDS_MYSQL_GITEA_DATABASE}
      MYSQL_USER: ${TDS_MYSQL_GITEA_USER}
      MYSQL_PASSWORD: ${TDS_MYSQL_GITEA_PASSWORD}
    volumes:
      - "tds-giteadb-data:/var/lib/mysql"
    labels:
      traefik.enable: "false"

  #-- CD/CI

  tds_drone:
    env_file: .env
    image: drone/drone:1.0.0-rc.5
    container_name: "tds_drone"
    privileged: true
    restart: always
    stop_grace_period: 30s
    depends_on:
      - tds_gitea
    links:
      - tds_gitea
    networks:
      private:
        aliases:
          - drone.${TDS_DOMAINNAME}
          - tds_drone
      public:
        aliases:
          - drone.${TDS_DOMAINNAME}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./services/drone/public/css:/public/css"
      - "tds-drone-data:/data"
    environment:
      - DRONE_DEBUG=false
      - DRONE_GITEA_SERVER=http://gitea.${TDS_DOMAINNAME}:3000
      - DRONE_GITEA_URL=http://gitea.${TDS_DOMAINNAME}:3000
      - DRONE_GITEA_PRIVATE_MODE=true
      - DRONE_GITEA_SKIP_VERIFY=true
      - DRONE_GIT_ALWAYS_AUTH=true
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NETWORKS=tds_public
      - DRONE_SERVER_HOST=drone.${TDS_DOMAINNAME}
      - DRONE_SERVER_PROTO=http
      - DRONE_NETWORK=tds_public
      - DRONE_TLS_AUTOCERT=false
      - DRONE_USER_CREATE=username:${TDS_DRONE_ADMIN_USER},admin:true
      - DRONE_LOGS_COLOR=true
      - DRONE_LOGS_DEBUG=true
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_NOCOLOR=false
    labels:
      traefik.enable: "true"
      traefik.backend: "tds_drone"
      traefik.docker.network: "tds_public"
      traefik.port: "80"
      traefik.frontend.entryPoints: "http"
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.rule: "Host: drone.${TDS_DOMAINNAME}, www.drone.${TDS_DOMAINNAME}"

volumes:
  tds-portainer-data:
  tds-mailhog-data:
  tds-gitea-data:
  tds-giteadb-data:
  tds-drone-data:

networks:
  public:
    driver: bridge
    name: tds_public
  private:
    name: tds_private
