version: "3.6"
services:

  gitea:
    env_file: ../.env
    image: gitea/gitea:latest
    container_name: "gitea"
    domainname: ${TDS_DOMAINNAME}
    hostname: "gitea"
    restart: always
    stop_grace_period: 30s
    ports:
      - ${TDS_GIT_SSHPORT}:22/tcp
    networks:
      private:
        aliases:
          - gitea
          - git
      public:
        aliases:
          - gitea.${TDS_DOMAINNAME}
          - git.${TDS_DOMAINNAME}
    environment:
      APP_NAME: "${TDS_BRANDING_COMPANY_NAME} GIT Versioning Server"
      RUN_MODE: dev
      SSH_DOMAIN: gitea.${TDS_DOMAINNAME}
      SSH_PORT: ${TDS_GIT_SSHPORT}
      DISABLE_SSH: "false"
      HTTP_PORT: 3000
      ROOT_URL: "http://gitea.${TDS_DOMAINNAME}"
      DB_TYPE: mysql
      DB_HOST: gitdb.${TDS_DOMAINNAME}:3306
      DB_NAME: gitea
      DB_USER: ${TDS_MYSQL_GITEAUSER}
      DB_PASSWD: ${TDS_MYSQL_GITEAPWD}
      INSTALL_LOCK: "FALSE"
      DISABLE_REGISTRATION: "FALSE"
      REQUIRE_SIGNIN_VIEW: "TRUE"
      USER_UID: ${TDS_GIT_USER_UID}
      USER_GID: ${TDS_GIT_USER_GID}
    depends_on:
      - giteadb
    volumes:
      - "${TDS_VOLUMEDIR}/gitea/data:/data"
      - "${TDS_GIT_REPO_DIR}:/data/git/repositories"
    labels:
      traefik.enable: "true"
      traefik.backend: "gitea"
      traefik.docker.network: "public"
      traefik.port: "3000"
      traefik.frontend.rule: "Host: gitea.${TDS_DOMAINNAME}"

  giteadb:
    image: mariadb:latest
    container_name: "giteadb"
    domainname: ${TDS_DOMAINNAME}
    hostname: "giteadb"
    restart: always
    stop_grace_period: 30s
    networks:
      private:
        aliases:
          - gitdb
      public:
        aliases:
          - gitdb.${TDS_DOMAINNAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${TDS_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${TDS_MYSQL_GITEAUSER}
      MYSQL_PASSWORD: ${TDS_MYSQL_GITEAPWD}
      MYSQL_DATABASE: gitea
    volumes:
      - "${TDS_VOLUMEDIR}/gitea/mysql:/var/lib/mysql"

networks:
  public:
    external:
      name: public
  private:
    external:
      name: private
