version: "3.6"
services:

  mailhog:
    env_file: ../.env
    image: mailhog/mailhog:latest
    container_name: "mailhog"
    restart: always
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    networks:
      private:
        aliases:
          - mailhog
          - mail
      public:
        aliases:
         - mailhog.${TDS_DOMAINNAME}
         - mail.${TDS_DOMAINNAME}
    volumes:
      - "${TDS_VOLUMEDIR}/mailhog/mails:/maildir"
    labels:
      traefik.enable: "true"
      traefik.backend: "mailhog"
      traefik.docker.network: "public"
      traefik.port: "8025"
      traefik.frontend.rule: "Host:mail.${TDS_DOMAINNAME}"

networks:
  public:
    external:
      name: public
  private:
    external:
      name: private
