version: "3.6"
services:

  pma:
    env_file: ../.env
    image: phpmyadmin/phpmyadmin:latest
    container_name: "pma"
    hostname: pma
    domainname: ${TDS_DOMAINNAME}
    restart: always
    networks:
      private:
        aliases:
          - pma
      public:
        aliases:
          - pma.${TDS_DOMAINNAME}
    external_links:
      - giteadb
    environment:
      PMA_ABSOLUTE_URI: "http://pma.${TDS_DOMAINNAME}"
      PMA_HOSTS: "gitdb.${TDS_DOMAINNAME}"
      PMA_PORT: "3306"
      PHP_UPLOAD_MAX_FILESIZE: "1G"
      PHP_MAX_INPUT_VARS: "1G"
      MYSQL_ROOT_PASSWORD: ${TDS_MYSQL_ROOT_PASSWORD}
    labels:
      traefik.enable: "true"
      traefik.backend: "pma"
      traefik.docker.network: "public"
      traefik.port: "80"
      traefik.frontend.rule: "Host:pma.${TDS_DOMAINNAME}"

networks:
  public:
    external:
      name: public
  private:
    external:
      name: private
