version: "3.6"
services:

  traefik:
    env_file: ../.env
    image: traefik:latest
    hostname: proxy
    domainname: ${TDS_DOMAINNAME}
    container_name: "proxy"
    restart: always
    command: --api --docker
    ports:
      - 80:80/tcp
      - 443:443/tcp
    networks:
      private:
        aliases:
          - traefik
          - proxy
      public:
        aliases:
         - traefik.${TDS_DOMAINNAME}
         - proxy.${TDS_DOMAINNAME}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${TDS_VOLUMEDIR}/traefik/traefik.toml:/traefik.toml"
      - "${TDS_VOLUMEDIR}/traefik/certs/:/certs/"
#     - "${TDS_VOLUMEDIR}/.config/traefik/:/acme.json"
    labels:
      traefik.enable: "true"
      traefik.backend: "proxy"
      traefik.docker.network: "public"
      traefik.port: "8080"
      traefik.frontend.rule: "Host:proxy.${TDS_DOMAINNAME}"

networks:
  public:
    driver: bridge
    name: public
  private:
    name: private
