version: "3.6"
services:

  tds_gitea:
    env_file: .env
    image: gitea/gitea:latest
    container_name: "tds_gitea"
    domainname: ${TDS_DOMAINNAME}
    hostname: "gitea"
    restart: always
    stop_grace_period: 30s
    ports:
      - 3000:3000/tcp
      - ${TDS_GITEA_SSHPORT}:22/tcp
    networks:
      private:
        aliases:
          - gitea.${TDS_DOMAINNAME}
          - tds_gitea
          - gitea
      public:
        aliases:
          - gitea.${TDS_DOMAINNAME}
    external_links:
      - tds_proxy
    environment:
      APP_NAME: "${TDS_BRANDING_NAME} GIT Versioning Server"
      RUN_MODE: prod
      PROTOCOL: "http"
      DOMAIN: gitea.${TDS_DOMAINNAME}
      ROOT_URL: "http://gitea.${TDS_DOMAINNAME}:3000"
      HTTP_ADDR: 0.0.0.0
      HTTP_PORT: 3000
      DISABLE_SSH: "FALSE"
      START_SSH_SERVER: "TRUE"
      SSH_DOMAIN: gitea.${TDS_DOMAINNAME}
      SSH_PORT: ${TDS_GITEA_SSHPORT}
      SSH_LISTEN_PORT: ${TDS_GITEA_SSHPORT}
      OFFLINE_MODE: "FALSE"
      ENABLE_GZIP: "TRUE"
      LANDING_PAGE: explore
      DB_TYPE: mysql
      DB_HOST: tds_giteadb:3306
      DB_NAME: ${TDS_MYSQL_GITEA_DATABASE}
      DB_USER: ${TDS_MYSQL_GITEA_USER}
      DB_PASSWD: ${TDS_MYSQL_GITEA_PASSWORD}
      INSTALL_LOCK: "FALSE"
      DISABLE_REGISTRATION: "FALSE"
      REQUIRE_SIGNIN_VIEW: "TRUE"
      USER_UID: ${TDS_GITEA_USER_UID}
      USER_GID: ${TDS_GITEA_USER_GID}
    volumes:
      - "tds-gitea-data:/data"
      - "./public:/data/gitea/public"
      - "${TDS_REPO_DIR}:/data/git/repositories"
    labels:
      traefik.enable: "true"
      traefik.backend: "tds_gitea"
      traefik.docker.network: "tds_public"
      traefik.port: "3000"
      traefik.frontend.entryPoints: "http"
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.rule: "Host: gitea.${TDS_DOMAINNAME}, www.gitea.${TDS_DOMAINNAME}"

  tds_giteadb:
    env_file: .env
    image: mariadb:latest
    container_name: "tds_giteadb"
    domainname: ${TDS_DOMAINNAME}
    hostname: "tds_giteadb"
    restart: always
    stop_grace_period: 30s
    networks:
      private:
        aliases:
          - tds_giteadb
          - giteadb
    environment:
      MYSQL_ROOT_PASSWORD: ${TDS_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${TDS_MYSQL_GITEA_DATABASE}
      MYSQL_USER: ${TDS_MYSQL_GITEA_USER}
      MYSQL_PASSWORD: ${TDS_MYSQL_GITEA_PASSWORD}
    volumes:
      - "tds-giteadb-data:/var/lib/mysql"
    labels:
      traefik.enable: "false"

volumes:
  tds-gitea-data:
  tds-giteadb-data:

networks:
  public:
    external:
      name: tds_public
  private:
    external:
      name: tds_private
