#Traefik Global Configuration
debug = true
checkNewVersion = true
logLevel = "DEBUG"

[traefikLog]
filePath = "/var/log/traefik.log"

[accessLog]
accessLogsFile = "/var/log/access_traefik.log"

#Define the EntryPoint for HTTP and HTTPS
defaultEntryPoints = ["http","https"]

#Enable Traefik Dashboard on port 8080
#with basic authentication method
[web]
address = ":8080"
[web.auth.basic]
users = ["admin:$apr1$iE0pANfc$gobRdp3SqRLrkk9tuy7AT0"]

[docker]
watch = true
endpoint = "unix:///var/run/docker.sock"
exposedbydefault = false

#Define the HTTP port 80 and
#HTTPS port 443 EntryPoint
[entryPoints]
  [entryPoints.http]
  address = ":80"


  [entryPoints.https]
  address = ":443"

  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
      certFile = "/certs/wildcard.crt"
      keyFile = "/certs/wildcard.key"

  [entryPoints.proxy]
    address=":8080"
    [entryPoints.proxy.auth]
      [entryPoints.proxy.auth.basic]
        users = [
         "admin:$apr1$iE0pANfc$gobRdp3SqRLrkk9tuy7AT0"
        ]

[file]
watch = true
