version: "3.6"
services:

  tds_pma:
    env_file: .env
    image: phpmyadmin/phpmyadmin:latest
    container_name: "tds_pma"
    hostname: pma
    domainname: ${TDS_DOMAINNAME}
    restart: always
    networks:
      private:
        aliases:
          - pma
      public:
        aliases:
          - pma.${TDS_DOMAINNAME}
    external_links:
      - tds_proxy
      - tds_giteadb
    environment:
      PMA_ABSOLUTE_URI: "https://pma.${TDS_DOMAINNAME}"
      PMA_HOSTS: "giteadb"
      PMA_PORT: "3306"
      PHP_UPLOAD_MAX_FILESIZE: "1G"
      PHP_MAX_INPUT_VARS: "1G"
      MYSQL_ROOT_PASSWORD: ${TDS_MYSQL_ROOT_PASSWORD}
    labels:
      traefik.enable: "true"
      traefik.backend: "pma"
      traefik.docker.network: "tds_public"
      traefik.port: "80"
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.entryPoints: "http,https"
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.rule: "Host: pma.${TDS_DOMAINNAME}, www.pma.${TDS_DOMAINNAME}"

networks:
  public:
    external:
      name: tds_public
  private:
    external:
      name: tds_private
